In [1]:
import torch.nn as nn

In [2]:
# 使用calculate_gain函数计算激活函数的增益
gain = nn.init.calculate_gain('relu', 0.2)
print(gain)

1.4142135623730951


In [4]:
# 初始化一个张量
import torch
tensor = torch.randn(3, 3)

In [8]:
# 参数初始化函数签名，及一些常见的初始化算法
torch.nn.init.uniform_(tensor,a=0.0,b=1.0) # 常数初始化，该函数将对tensor中的元素进行均匀分布初始化，范围为[a,b]

tensor([[0.2460, 0.0016, 0.0090],
        [0.7510, 0.6679, 0.5738],
        [0.6945, 0.6971, 0.0320]])

In [9]:
nn.init.normal_(tensor,mean=0.0,std=1.0) # 常数初始化，该函数将对tensor中的元素进行正态分布初始化，均值为mean，标准差为std

tensor([[ 1.3649, -0.1176,  1.5783],
        [-0.2903, -0.8175, -0.6393],
        [ 1.4862, -0.8554, -1.2225]])

In [10]:
# 使用服从Glorot均匀分布的随机数初始化张量
nn.init.xavier_uniform_(tensor, gain=1.0) # 调用希维尔均匀分布初始化函数，gain为增益量

tensor([[-0.8729, -0.2137, -0.6302],
        [-0.8743, -0.7039, -0.1883],
        [-0.3171,  0.1039,  0.9299]])

In [11]:
# 调用希维尔正态分布初始化函数，gain为增益量
nn.init.xavier_normal_(tensor, gain=1.0)

tensor([[ 0.6076,  0.3423,  0.2416],
        [ 0.1613,  0.9751,  1.0417],
        [ 0.1566,  0.0529, -0.2632]])

In [12]:
# 调用kaiming均匀分布初始化函数
# mode为执行模式，nonlinearity为激活函数，a为增益量
nn.init.kaiming_uniform_(tensor, a=0, mode='fan_in', nonlinearity='leaky_relu')

tensor([[-0.7390, -0.8865,  0.5460],
        [ 0.0359,  0.1163,  0.1936],
        [-0.1725, -0.8985,  0.1238]])

### [对于Leaky Relu和Relu的区别分析](https://blog.csdn.net/sinat_33027857/article/details/80192789)
1. Relu：  
   - 数学表达式：a = max(0, z)  
   - 函数图像为：
   - 函数图像：  
<br>
![ReLU](https://img-blog.csdn.net/20180504113419900?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NpbmF0XzMzMDI3ODU3/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)  
   - 优点：由上图可以看出，Relu得到的SGD的收敛速度较快   
   - 缺点：训练的时候很容易‘die'了，对于小于0的值，这个神经元的梯度永远都会是0，在实际操错中，如果learning rate很大，很可能网络中较多的神经元都'dead'了，即使是较小的learning rate，这种情况也很有可能发生。

2. Leaky Relu：
   - 数学表达式：y = max(0, x) + leak*min(0,x)  （leak是一个很小的常数，这样保留了一些负轴的值，使得负轴的信息不会全部丢失）
   - 函数图像：  
   ![Leaky ReLU](https://img-blog.csdn.net/20180504113452899?watermark/2/text/aHR0cHM6Ly9ibG9nLmNzZG4ubmV0L3NpbmF0XzMzMDI3ODU3/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70)