In [1]:
import torch

In [2]:
# 生成一个3,4,5的随机正态分布张量
x = torch.randn(3, 4, 5)

In [3]:
# 使用.ndimension()查看张量的维度
print(x.ndimension())

3


In [4]:
# 使用.size()查看张量的形状
print(x.size())

torch.Size([3, 4, 5])


In [7]:
# 同样于上面的方法，使用.shape查看张量的形状
print(x.shape)

torch.Size([3, 4, 5])


In [10]:
# 向量改变形状为3行4列的矩阵
x = torch.randn(12)
x

tensor([ 1.0475,  1.2772,  0.4431,  1.0769,  0.8359,  0.8925,  0.8044,  0.7583,
         1.3134, -0.3365, -0.3759,  0.9687])

In [11]:
x.view(3, 4)

tensor([[ 1.0475,  1.2772,  0.4431,  1.0769],
        [ 0.8359,  0.8925,  0.8044,  0.7583],
        [ 1.3134, -0.3365, -0.3759,  0.9687]])

In [12]:
x

tensor([ 1.0475,  1.2772,  0.4431,  1.0769,  0.8359,  0.8925,  0.8044,  0.7583,
         1.3134, -0.3365, -0.3759,  0.9687])

可以看到：.view()函数并不能改变原始张量的形状，而仅仅是在原始张量的基础之上，创建了一个新的张量。  
同样的，如果当.view()函数中的第一个维度传入为-1时，它会同Numpy一样自动计算该张量的第一个维度的大小。

In [13]:
# 验证
x.view(-1, 4)

tensor([[ 1.0475,  1.2772,  0.4431,  1.0769],
        [ 0.8359,  0.8925,  0.8044,  0.7583],
        [ 1.3134, -0.3365, -0.3759,  0.9687]])

In [14]:
# 获取张量的数据指针
x.data_ptr()

94829144937920

In [16]:
# 交换张量的维度
x.view(3,4).transpose(0,1)

tensor([[ 1.0475,  0.8359,  1.3134],
        [ 1.2772,  0.8925, -0.3365],
        [ 0.4431,  0.8044, -0.3759],
        [ 1.0769,  0.7583,  0.9687]])

In [18]:
# 同样于Numpy，我们可以使用.T属性获得转置后的张量，但是这并不等于维度交换
x.view(3,4).T

tensor([[ 1.0475,  0.8359,  1.3134],
        [ 1.2772,  0.8925, -0.3365],
        [ 0.4431,  0.8044, -0.3759],
        [ 1.0769,  0.7583,  0.9687]])

In [20]:
# 当步长和维度不相兼容时，将使用contiguous()函数重新生成张量，此时x的数据指针将会发生变化
x.view(3,4).transpose(0,1).contiguous().data_ptr()

94829145416064

In [21]:
x = x.view(3,4).transpose(0,1).contiguous()
x

tensor([[ 1.0475,  0.8359,  1.3134],
        [ 1.2772,  0.8925, -0.3365],
        [ 0.4431,  0.8044, -0.3759],
        [ 1.0769,  0.7583,  0.9687]])

In [23]:
# 对x使用切片索引
x[1,1]

tensor(0.8925)

In [33]:
t = torch.randint(0,2,(3,3),device='cuda')
t

tensor([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 1]], device='cuda:0')

In [34]:
# 实现条件索引
t[t == 1]

tensor([1, 1, 1, 1, 1, 1], device='cuda:0')

In [35]:
# 释放显存
torch.cuda.empty_cache()

In [36]:
t2 = t.clone()

In [37]:
t2

tensor([[1, 0, 0],
        [1, 1, 1],
        [0, 1, 1]], device='cuda:0')