In [1]:
import torch

In [2]:
# 创建一个正态分布张量
a = torch.randn(2, 3)

In [3]:
# 快速开方：调用矩阵内置函数
a.sqrt()

tensor([[1.1324, 0.7684, 1.0883],
        [0.5606, 0.7870, 0.6999]])

In [4]:
# 快速开方：torch.sqrt()
torch.sqrt(a)

tensor([[1.1324, 0.7684, 1.0883],
        [0.5606, 0.7870, 0.6999]])

In [5]:
# 开方后修改原张量
torch.sqrt_(a)

tensor([[1.1324, 0.7684, 1.0883],
        [0.5606, 0.7870, 0.6999]])

In [6]:
a

tensor([[1.1324, 0.7684, 1.0883],
        [0.5606, 0.7870, 0.6999]])

In [7]:
# 指定维度的求和
a.sum(dim=0)

tensor([1.6931, 1.5554, 1.7882])

In [8]:
# 或者使用torch.sum(tensor,dim)
torch.sum(a,0)

tensor([1.6931, 1.5554, 1.7882])

In [9]:
# 对多维元素进行计算
torch.mean(a,[0,1])

tensor(0.8394)

In [10]:
# 实现多个矩阵内的计算
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
t1.add(t2)

tensor([[1.4034, 0.7676, 1.7710],
        [1.0272, 0.3928, 0.6179]])

In [11]:
# 当同阶数的张量进行计算时，也可以直接使用算术运算符
t1 + t2

tensor([[1.4034, 0.7676, 1.7710],
        [1.0272, 0.3928, 0.6179]])

In [12]:
# 使用下划线函数覆盖原始张量
t1.add_(t2)

tensor([[1.4034, 0.7676, 1.7710],
        [1.0272, 0.3928, 0.6179]])

In [13]:
t1

tensor([[1.4034, 0.7676, 1.7710],
        [1.0272, 0.3928, 0.6179]])

In [14]:
# 创建一个3x4的张量
t3 = torch.randn(3,4)

In [15]:
# 使用.argmax()函数获取最大值的索引，接受两个参数，第一位是原始矩阵，第二位是维度，指定.argmax()将以哪一维度进行最值计算
t3.argmax(dim=0)

tensor([0, 0, 0, 0])

In [16]:
# 使用外置函数
torch.argmax(t3,dim=0)

tensor([0, 0, 0, 0])

In [17]:
# 函数调用，返回的是沿着最后一个维度，包含极大值和极大值所在的位置的元组
torch.max(t3,-1)

torch.return_types.max(
values=tensor([2.1130, 0.0412, 0.3876]),
indices=tensor([2, 3, 0]))

In [18]:
torch.min(t3,-1)

torch.return_types.min(
values=tensor([-1.0264, -1.0804, -1.8929]),
indices=tensor([1, 1, 3]))

In [19]:
# 内置方法调用，返回的是沿着第0个维度，包含极小值和极小值所在的位置
t3.min(0)

torch.return_types.min(
values=tensor([-0.4101, -1.5239, -0.1773, -1.8929]),
indices=tensor([1, 2, 2, 2]))

In [20]:
# 沿着最后一个维度排序，返回排序后的张量和张量元素在该维度的原始位置
t3.sort(-1)

torch.return_types.sort(
values=tensor([[-1.0264,  0.9223,  1.8308,  2.1130],
        [-1.0804, -0.4101, -0.1396,  0.0412],
        [-1.8929, -1.5239, -0.1773,  0.3876]]),
indices=tensor([[1, 3, 0, 2],
        [1, 0, 2, 3],
        [3, 1, 2, 0]]))