In [1]:
import torch

In [2]:
# 创建一个正态分布张量
a = torch.randn(2, 3)

In [3]:
# 快速开方：调用矩阵内置函数
a.sqrt()

tensor([[0.6800,    nan, 0.7629],
        [0.3994,    nan,    nan]])

In [4]:
# 快速开方：torch.sqrt()
torch.sqrt(a)

tensor([[0.6800,    nan, 0.7629],
        [0.3994,    nan,    nan]])

In [5]:
# 开方后修改原张量
torch.sqrt_(a)

tensor([[0.6800,    nan, 0.7629],
        [0.3994,    nan,    nan]])

In [6]:
a

tensor([[0.6800,    nan, 0.7629],
        [0.3994,    nan,    nan]])

In [7]:
# 指定维度的求和
a.sum(dim=0)

tensor([1.0793,    nan,    nan])

In [8]:
# 或者使用torch.sum(tensor,dim)
torch.sum(a,0)

tensor([1.0793,    nan,    nan])

In [9]:
# 对多维元素进行计算
torch.mean(a,[0,1])

tensor(nan)

In [10]:
# 实现多个矩阵内的计算
t1 = torch.rand(2,3)
t2 = torch.rand(2,3)
t1.add(t2)

tensor([[1.5297, 0.8385, 1.1277],
        [0.6665, 1.1280, 1.1690]])

In [11]:
# 当同阶数的张量进行计算时，也可以直接使用算术运算符
t1 + t2

tensor([[1.5297, 0.8385, 1.1277],
        [0.6665, 1.1280, 1.1690]])

In [12]:
# 使用下划线函数覆盖原始张量
t1.add_(t2)

tensor([[1.5297, 0.8385, 1.1277],
        [0.6665, 1.1280, 1.1690]])

In [13]:
t1

tensor([[1.5297, 0.8385, 1.1277],
        [0.6665, 1.1280, 1.1690]])

In [15]:
# 创建一个3x4的张量
t3 = torch.randn(3,4)

In [16]:
# 使用.argmax()函数获取最大值的索引，接受两个参数，第一位是原始矩阵，第二位是维度，指定.argmax()将以哪一维度进行最值计算
t3.argmax(dim=0)

tensor([1, 0, 2, 2])

In [18]:
# 使用外置函数
torch.argmax(t3,dim=0)

tensor([1, 0, 2, 2])

In [19]:
# 函数调用，返回的是沿着最后一个维度，包含极大值和极大值所在的位置的元组
torch.max(t3,-1)

torch.return_types.max(
values=tensor([1.9638, 0.3869, 1.0469]),
indices=tensor([1, 0, 3]))

In [20]:
torch.min(t3,-1)

torch.return_types.min(
values=tensor([-2.0375, -1.0223, -0.9280]),
indices=tensor([2, 2, 0]))