In [1]:
import torch

In [2]:
# 初始化一个3x3的张量，设置requires_grad=True实现自动求导
t1 = torch.randn(3,3,requires_grad=True)

In [3]:
t1

tensor([[-0.1012, -1.1604,  1.2453],
        [-1.6585, -0.2628,  0.6272],
        [ 1.7388, -0.3195,  0.3537]], requires_grad=True)

In [4]:
# 使用t1.grad查看梯度，由于我们没有进行反向传播，所以梯度为None
t1.grad

In [5]:
# 我们定义一个函数为：f(x) = x^2，所以它的导数根据公式应为：f'(x) = 2x
t2 = t1.pow(2).sum()

In [6]:
# 反向传播给t1
t2.backward()

In [7]:
# 查询t1的梯度
t1.grad

tensor([[-0.2024, -2.3208,  2.4907],
        [-3.3171, -0.5256,  1.2543],
        [ 3.4776, -0.6389,  0.7074]])

In [8]:
# 再次计算所有分量的平方和
t2 = t1.pow(2).sum()
# 再次执行反向传播
t2.backward()

In [9]:
# 再次查询t1的梯度
t1.grad

tensor([[-0.4048, -4.6416,  4.9814],
        [-6.6341, -1.0512,  2.5086],
        [ 6.9552, -1.2778,  1.4147]])

In [10]:
# 重新初始化t1
t1 = torch.randn(3,3,requires_grad=True)
t2 = t1.pow(2).sum() # 根据t1张量计算t2张量
torch.autograd.grad(t2, t1) # t2张量对t1张量求导

(tensor([[ 2.1634, -1.9463, -0.4436],
         [ 0.6815, -2.1217,  0.3258],
         [-1.7609, -0.9381,  4.3381]]),)

In [11]:
# 重新初始化t1
t1 = torch.randn(3,3,requires_grad=True)
t2 = t1.sum()
t2 # t2的计算构建了计算图，输出结果带有grad_fn

tensor(4.0789, grad_fn=<SumBackward0>)

In [12]:
# 使用torch.no_grad()来禁止构建计算图
with torch.no_grad():
    t3 = t1.sum()
# 输出结果不带有grad_fn
t3

tensor(4.0789)

In [13]:
# 保持原来的计算图
t1.sum()

tensor(4.0789, grad_fn=<SumBackward0>)

In [14]:
# 使用detach()函数和原来的计算图分离
t1.sum().detach()

tensor(4.0789)